<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>

</body>

</html>
<script src="./jquery-3.3.1.js"></script>
<script>
    /*   $.ajax({
          url:'./data.json',
          success:function(){
              $.ajax({
                  url:'./data.json',
                  success:function(){
                      
                  }
              })
          }
      }) */

    //executor
    //       Promise  实例有三个状态 分别是 pending  resolved    reject
    //       pending  代表当前的peomise 还是 处在 等待状态
    //       resolved 代表当前走了成功的回调函数
    //       reject  代表当前走了失败的回调函数
    let p = new Promise(function (resolve, reject) {
        //resolve 是执行成功的对应的回调函数  
        //reject 是执行失败的对应的回调函数
        //具体是执行 成功 或者 失败 是由书写executor函数的这个人决定的
        setTimeout(() => {
            reject(123)
            // resolve(123);
        }, 3000);
    });
    // console.log(p) 
    // then 接收两个函数作为参数  第一个函数对应  resolve  第二个函数对应 reject
    p.then(function (data) {
        console.log(data)
    }, function (err) {
        console.log(err)
    })
    p.then(function (data) {
        console.log('success')
        console.log(data);
    }, function (err) {
        console.log('error')
        console.log(err)
        console.log(aaa)
    }).then(function (data2) {
        console.log('data2', data2)
    }, function (err2) {
        console.log('err2', err2)
    });

    /*  let p = new Promise(function (resolve, reject) {
         $.ajax({
             url: './data.json',
             success: res,
             error: rej
         })
     }); */
    p.then(function (data) {
        //then 可以写两个参数 也可以写一个参数  对应的是成功的回调  失败信息我们可以通过 catch捕获
        console.log(data);
        return 666666
    }).then(function (data2) {
        console.log(data2)
    }).catch(function (err) {
        console.log(err)
    })

    new Promise(function (res, rej) {
        res(123)
    }).then((data) => {
        console.log(data)
    }).catch((err) => {
        console.log(err)
    }).finally((data) => {
        console.log(data)
    })
    console.log(999999)
</script>